### ISSUE TITLE
Test model?

### ISSUE THREAD

**Issue by avighi** [jurader/covid19_xp#1]
How load model and predict?
Thanks

**Comment by jurader** [comment]
Code for training and inference are unified in run.py. Please modify run.py for saving and testing model. 



     ----- Original Message -----

**Comment by avighi** [comment]
I've saved .h5 model
I didn't understand how to load the model, import an image and check the result.
i tried to run tests and i get results like this:
[[0.00757184 0.05118135 0.9412468 ]]
what does it mean?

thanks

**Comment by jurader** [comment]
I am sorry that I cannot explain the way to use Keras model.Please refer to keras.io for documentation of Keras model.
https://keras.io/






     ----- Original Message -----

**Comment by avighi** [comment]
Ok thanks, I followed the documentation but I always get the result for the same class.
This is why I was asking the question, I did not understand how to interpret the result

**Comment by jurader** [comment]
Please use 
covid19_inference_with_pretrained.ipynb 
on my repo. (https://github.com/jurader/covid19_xp). 

In my model, the relationship between prediction results and disease name is as follows. 

0 => normal 
1 => non-covid19 pneumonia
2 => covid19

If you would like to predict your own data, please create your dataset as my own dataset. 
Please see ../preprocessed/n1000__shuffle1_seed123/test.csv in Colab for my own dataset. 




----- Original Message -----

**Comment by avighi** [comment]
Thankssssss
