### ISSUE TITLE
Epoch issue

### ISSUE THREAD

**Issue by avighi** [jurader/covid19_xp#3]
Epochs set to 100 but train process stops first.
Why?
thanks

**Comment by jurader** [comment]
Because early stopping is enabled.  



     ----- Original Message -----
 From: Andrea Vighi ***@***.***>
 To: jurader/covid19_xp ***@***.***> 
Cc: Subscribed ***@***.***>
 Date: 2021/4/18, Sun 05:58
 Subject: [jurader/covid19_xp] Epoch issue (#3)
   
Epochs set to 100 but train process stops first.
Why?
thanks—

**Comment by avighi** [comment]
What is the argument in .py?
Thanks

**Comment by jurader** [comment]
The following command is used in ipynb. 

! python3 -u run.py -o ./result/best__vgg/ -l 220 -b 8 -e 100 -z 125 -r 0.0001 --op 3 --dlr 15 -f 416 -d 0.1 --tf vg -v 0.55 --aug 4 --alpha 0.1 --beta 0.0 --verbose 1 --es 7 --index 1 --save 1 --eval-test 1


--es is the argument for early stopping. 



----- Original Message -----
