### ISSUE TITLE
Issue if I use another pre-trained model

### ISSUE THREAD

**Issue by avighi** [jurader/covid19_xp#4]
Why if I use resnet, exception or another model (not VGG), the val_loss is over 1 and the confusion matrix is wrong?
thanks

**Comment by jurader** [comment]
The optimal hyperparameters were different between models. For example, I used the following options for Resnet. 
-l 196 -b 20 -e 100 -z 50 -r 0.00001 --op 3 --dlr 15 -f 320 -d 0.0 --tf re -v 0.0 --aug 4 --alpha 0.0 --beta 0.0 --eq 0 --inp 0 --verbose 2 --es 6 





     ----- Original Message -----
 From: Andrea Vighi ***@***.***>
 To: jurader/covid19_xp ***@***.***> 
Cc: Subscribed ***@***.***>
 Date: 2021/5/13, Thu 21:08
 Subject: [jurader/covid19_xp] Issue if I use another pre-trained model (#4)
   
Why if I use resnet, exception or another model (not VGG), the val_loss is over 1 and the confusion matrix is wrong?
thanks—
