### ISSUE TITLE
Cannot run the inference file as you suggested. A lot of errors.

### ISSUE THREAD

**Issue by makhanov** [jurader/covid19_xp#5]
Can you please rerun your notebook? It does not work. I cannot recreate your results. Thus, I should write in my paper that your results are not reliable.

**Comment by jurader** [comment]
Please write error message. 
Results of my paper were not obtained using inference code of ipynb.(Inference code of ipynb was created based on the request.)Therefore, if my inference code of ipynb is wrong, it does not mean that my results are not reliable. 
Maybe, version up of google colab causes error.




     ----- Original Message -----
 From: Nursultan ***@***.***>
 To: jurader/covid19_xp ***@***.***> 
Cc: Subscribed ***@***.***>
 Date: 2021/6/10, Thu 21:53
 Subject: [jurader/covid19_xp] Cannot run the inference file as you suggested. A lot of errors. (#5)
   
Can you please rerun your notebook? It does not work. I cannot recreate your results. Thus, I should write in my paper that your results are not reliable.—

**Comment by makhanov** [comment]
Thank you for solving!
